# Generated by Django 5.1.2 on 2025-09-06 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vision',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('teen', 'Teen'), ('20s', '20s'), ('30s', '30s'), ('40s', '40s'), ('50s', '50s'), ('60plus', '60+')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Non-binary'), ('na', 'Prefer not to say')], max_length=20)),
                ('region', models.CharField(blank=True, choices=[('se_asia', 'Southeast Asia'), ('e_asia', 'East Asia'), ('s_asia', 'South Asia'), ('middle_east', 'Middle East'), ('europe', 'Europe'), ('africa', 'Africa'), ('n_america', 'North America'), ('latam', 'Latin America'), ('oceania', 'Oceania'), ('na', 'Prefer not to say')], max_length=20)),
                ('style_keywords', models.CharField(blank=True, help_text="Comma-separated (e.g. 'minimalist, cinematic, soft lighting')", max_length=200)),
                ('consent_use_demographics', models.BooleanField(default=False, help_text='Allow using age/region/gender to tailor generated images.')),
                ('onboarded', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
